-- Migration: 047_fix_news_url_ownership (SUPERSEDED — no-op)
--
-- This migration originally reassigned news/events by bare-hostname matching.
-- It used REGEXP_REPLACE(url, '/.*$', '') which stripped the entire path,
-- producing keys like 'facebook.com' instead of 'facebook.com/pagename/events'.
-- Any POI with a Facebook events_url would "own" ALL facebook.com content.
--
-- The runtime URI ownership code (buildUriOwnershipMap + checkUriOwnership in
-- newsService.js) was fixed in PR #521 to use full URI prefixes (hostname+path).
-- This migration re-ran on every container start and overwrote those correct
-- assignments, causing the recurring GVB content misattribution bug.
--
-- Removed: 2026-06-26. Runtime handles URI ownership at save time.
